name: deploy backend

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 202.120.40.8
        username: root
        port: 30550
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        script: |
          ls
